Update Build_App_Dev.yml

diff --git a/.github/workflows/Build_App_Dev.yml b/.github/workflows/Build_App_Dev.yml
--- a/.github/workflows/Build_App_Dev.yml
+++ b/.github/workflows/Build_App_Dev.yml
@@ -25,7 +25,7 @@ jobs:
         run: |
           cat .env
           echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u qnx-dev --password-stdin
-          docker pull $IMAGE_TAG
+          docker pull $IMAGE_TAG || echo "Image not found, proceeding with build."
           docker build --cache-from $IMAGE_TAG -t $IMAGE_TAG .
           docker push $IMAGE_TAG
         env:
